service: iplayer-sounds-skill

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1 

  # Define environment variables for the Lambda function
  environment:
    SOUNDS_TABLE_NAME: ${self:custom.soundsTableName} # Pass table name to function

  # Define IAM permissions for the Lambda function
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:Query"       # Allow querying the table
            # - "dynamodb:GetItem"
            # - "dynamodb:PutItem"
          Resource:
            - "Fn::GetAtt": [ SoundsDynamoDbTable, Arn ] # Grant permission specifically to our table ARN

functions:
  api:
    handler: .build/src/handler.handler
    events:
      - alexaSkill:

# Custom variables section
custom:
  soundsTableName: iplayer-sounds-data-${sls:stage} # Define table name using stage

# Define AWS resources (Infrastructure as Code)
resources:
  Resources:
    SoundsDynamoDbTable: # Logical ID for the DynamoDB Table
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.soundsTableName} # Set the actual table name
        AttributeDefinitions:
          - AttributeName: soundKey # Define the primary key attribute
            AttributeType: S        # S = String type
        KeySchema:
          - AttributeName: soundKey
            KeyType: HASH           # HASH = Partition key
        # Define throughput. Use PAY_PER_REQUEST for simple/serverless scaling
        BillingMode: PAY_PER_REQUEST
        # PointInTimeRecoverySpecification:
        #   PointInTimeRecoveryEnabled: true